services:
  devops-intelligence:
    build: .
    container_name: devops-intelligence-center
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./chroma_data:/app/chroma_data # Persistent Vector Database (Knowledge Base Storage)
    restart: unless-stopped

networks:
  default:
    name: devops-net
